[theme]
base = "dark"
primaryColor = "#3B9EFF"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
runOnSave = false
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[runner]
magicEnabled = false
fastReruns = true